# Generated by Django 2.2.1 on 2019-06-04 08:32

import book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=5)),
                ('author', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('cost', models.PositiveIntegerField()),
                ('page_number', models.PositiveIntegerField()),
                ('isbn_number', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to=book.models.store_image)),
                ('file', models.FileField(blank=True, null=True, upload_to=book.models.store_file)),
                ('free', models.BooleanField(blank=True, default=False, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Category')),
            ],
        ),
    ]
